In [1]:
import ir_datasets

In [3]:
dataset = ir_datasets.load(f'bright/biology')

In [4]:
dataset.docs_count()

57359

In [5]:
for doc in dataset.docs_iter()[:10]:
  print(doc)

GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_0_43.txt', text=' pelvises; and proportionally shorter forearms and forelegs.\nBased on 45 Neanderthal long bones from 14 men and 7 women, the average height was 164 to 168\xa0cm (5\xa0ft 5\xa0in to 5\xa0ft 6\xa0in) for males and 152 to 156\xa0cm (5\xa0ft 0\xa0in to 5\xa0ft 1\xa0in) for females. For comparison, the average height of 20 males and 10 females Upper Palaeolithic humans is, respectively, 176.2\xa0cm (5\xa0ft 9.4\xa0in) and 162.9')
GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_0_119.txt', text=" Gorham's Cave, Gibraltar, were discovered, dated to older than 39,000 years ago, which the discoverers have interpreted as Neanderthal abstract art. The scratches could have also been produced by a bear. In 2021, an Irish elk phalanx with five engraved offset chevrons stacked above each other was discovered at the entrance to the Einhornhöhle cave in Germany, dating to about 51,000 years ago.\nIn 2018, some red-painted dots, disks, lines and hand stencils on the cave walls of the Spanish La Pasie")
GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_0_75.txt', text=' similar to modern hunter gatherers, and was born in the spring, which is consistent with modern humans and other mammals whose birth cycles coincide with environmental cycles. Indicated from various ailments resulting from high stress at a low age, such as stunted growth, British archaeologist Paul Pettitt hypothesised that children of both sexes were put to work directly after weaning; and Trinkaus said that, upon reaching adolescence, an individual may have been expected to join in hunting large and dangerous game. However, the bone trauma is comparable to modern Inuit, which could suggest a similar childhood between')
GenericDoc(doc_id='neanderthals_vitamin_C_diet/L-gulonolactone_oxidase_2.txt', text='Consequences of loss[edit]\nIt is likely that some level of adaptation occurred after the loss of the GULO gene by primates. Erythrocyte Glut1 and associated dehydroascorbic acid uptake modulated by stomatin switch are unique traits of humans and the few other mammals that have lost the ability to synthesize ascorbic acid from glucose. As GLUT transporters and stomatin are ubiquitously distributed in different human cell types and tissues, similar interactions may occur in human cells other than erythrocytes.\nLinus Pauling observed that after the loss of endogenous ascorbate production, apo(a) and Lp(a)  were greatly favored by evolution, acting as ascorbate surrogate, since the frequency of occurrence of elevated Lp(a) plasma levels in species that had lost the ability to synthesize ascorbate is great. Also, only primates share regulation of CAMP gene expression by vitamin D, which occurred after the loss of GULO gene.\nJohnson et al. have hypothesized that the mutation of the GULOP pseudogene so that it stopped producing GULO may have been of benefit to early primates by increasing uric acid levels and enhancing fructose effects on weight gain and fat accumulation. With a shortage of food supplies this gave mutants a survival advantage.')
GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_0_90.txt', text=' the high mortality rates. Alternatively, many more Neanderthals may have received burials, but the graves were infiltrated and destroyed by bears. Given that 20 graves of Neanderthals aged under 4 have been found—over a third of all known graves—deceased children may have received greater care during burial than other age demographics.\nLooking at Neanderthal skeletons recovered from several natural rock shelters, Trinkaus said that, although Neanderthals were recorded as bearing several trauma-related injuries, none of them had significant trauma to the legs that would debilitate movement. He suggested that self')
GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_0_1.txt', text='The type specimen, Neanderthal 1, was found in 1856 in the Neander Valley in present-day Germany.\nIt is not clear when the line of Neanderthals split from that of modern humans; studies have produced various times ranging from 315,000 to more than 800,000 years ago. The date of divergence of Neanderthals from their ancestor H. heidelbergensis is also unclear. The oldest potential Neanderthal bones date to 430,000 years ago, but the classification remains uncertain. Neanderthals are known from numerous fossils, especially from after 130,000 years ago.')
GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_5_31.txt', text=' The entire carcasses seem to have been transported to the cave and then butchered. Because this is such a large amount of food to consume before spoilage, it is possible these Neanderthals were curing and preserving it before winter set in. At 160,000 years old, it is the oldest potential evidence of food storage. The great quantities of meat and fat which could have been gathered in general from typical prey items (namely mammoths) could also indicate food storage capability. With shellfish, Neanderthals needed to eat, cook, or in some manner preserve them soon after collection')
GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_0_92.txt', text='als were once thought of as scavengers, but are now considered to have been apex predators. In 1980, it was hypothesised that two piles of mammoth skulls at La Cotte de St Brelade, Jersey, at the base of a gulley were evidence of mammoth drive hunting (causing them to stampede off a ledge), but this is contested. Living in a forested environment, Neanderthals were likely ambush hunters, getting close to and attacking their target—a prime adult—in a short burst of speed, thrusting in a spear at close quarters. Younger or wounded animals')
GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_3_0.txt', text='Demographics[edit]\n\nFurther information: Neanderthals in Southwest Asia, Neanderthals in Gibraltar, and List of Neanderthal sites\nRange[edit]\nNeanderthal skull from Tabun Cave, Israel, at the Israel Museum\nPre- and early Neanderthals, living before the Eemian interglacial (130,000 years ago), are poorly known and come mostly from Western European sites. From 130,000 years ago onwards, the quality of the fossil record increases dramatically with classic Neanderthals, who are recorded from Western, Central, Eastern and Mediterranean Europe')
GenericDoc(doc_id='neanderthals_vitamin_C_diet/Neanderthal_0_83.txt', text=' trends seen in obsidian transfer distance and tribe size in modern hunter-gatherers. However, according to their model Neanderthals would not have been as efficient at maintaining long-distance networks as modern humans, probably due to a significantly lower population. Hayden noted an apparent cemetery of six or seven individuals at La Ferrassie, France, which, in modern humans, is typically used as evidence of a corporate group which maintained a distinct social identity and controlled some resource, trading, manufacturing and so on. La Ferrassie is also located in one of the richest animal-migration routes of')

In [6]:
for query in dataset.queries_iter():
  print(query)

BrightQuery(query_id='0', text='Claim in article about why insects are attracted to light\nIn this article they are addressing the reason insects are attracted to light when they say\nHeat radiation as an attractive component is refuted by the effect of LED lighting, which supplies negligible infrared radiation yet still entraps vast numbers of insects.\nI don\'t see why attraction to LEDs shows they\'re not seeking heat. Could they for example be evolutionarily programmed to associate light with heat? So that even though they don\'t encounter heat near/on the LEDs they still "expect" to?', reasoning='The question probes why insects are drawn to low-heat LED lights, challenging the idea that their attraction to light is heat-based. The document helps distinguish between heat attraction and evolved behaviors, shedding light on why insects might be attracted to LEDs despite their minimal heat.', gold_answer="$\\begingroup$\n\nThey're looking for and describing _proximate_ relationships (see e.g. [\nhttps://en.wikipedia.org/wiki/Proximate_and_ultimate_causation\n](https://en.wikipedia.org/wiki/Proximate_and_ultimate_causation) ).\n\nIf the light isn't warm and insects still move towards it, that means they're\nnot _using heat_ to make the decision where to move. They're not saying\nanything about the ultimate underlying motives, just the immediate proximate\nmechanism.\n\nTheir alternative model is that it's based on orientation to the sky, by which\ninsects point the top of their body (dorsal surface) toward light; if the sky\nis bright that would keep them oriented back-upward, but if it's a point\nsource near the ground keeping their back towards the light causes them to fly\nin circles around the light:\n\n> Our guidance model demonstrates that this dorsal tilting is sufficient to\n> create the seemingly erratic flight paths of insects near lights and is the\n> most plausible model for why flying insects gather at artificial lights.\n\nSo, if you want to propose heat-seeking as a better hypothesis, you'd need to\nprovide data that would explain why this dorsal facing tilt would make sense\nfor an insect seeking heat.")
BrightQuery(query_id='1', text='Why do I only breathe out of one nostril?\nI was just sitting with my hand next to my nose and I realized that air was only coming out of the right nostril. Why is that? I would think I would use both, it seems much more efficient. Have I always only been breathing out of my right nostril?', reasoning="The post questions the normality of breathing primarily through one nostril. The chosen document explains the nasal cycle, a natural physiological process of alternating airflow between nostrils, directly addressing and normalizing the user's observation.", gold_answer="$\\begingroup$\n\nApparently you're not the first person to notice this; in 1895, a German nose\nspecialist called Richard Kayser found that we have tissue called erectile\ntissue in our noses (yes, it is very similar to the tissue found in a penis).\nThis tissue swells in one nostril and shrinks in the other, creating an open\nairway via only one nostril. What's more, he found that this is indeed a\n'nasal cycle', changing every 2.5 hours or so. Of course, the other nostril\nisn't completely blocked, just mostly. If you try, you can feel a very light\npush of air out of the blocked nostril.\n\nThis is controlled by the autonomic nervous system. You can change which\nnostril is closed and which is open by laying on one side to open the opposite\none.\n\nInterestingly, some researchers think that this is the reason we often switch\nthe sides we lay on during sleep rather regularly, as it is more comfortable\nto sleep on the side with the blocked nostril downwards.\n\nAs to why we don't breathe through both nostrils simultaneously, I couldn't\nfind anything that explains it.\n\nSources:  \n[ About 85% of People Only Breathe Out of One Nostril at a Time\n](http://www.todayifoundout.com/index.php/2010/03/about-85-of-people-only-\nbreathe-out-of-one-nostril-at-a-time/)  \n[ Nasal cycle ](http://en.wikipedia.org/wiki/Nasal_cycle)")
BrightQuery(query_id='2', text='Is there an RGB equivalent for smells?\nMillions of colors in the visible spectrum can be generated by mixing red, green and blue - the RGB color system. Is there a basic set of smells that, when mixed, can yield all, or nearly all detectable smells ?', reasoning='The query explores if basic smells can combine to replicate various odors, similar to RGB in color vision. The document details the human olfactory system and receptors, highlighting the complexity in odor detection and perception, where each receptor binds to multiple odors and each odor interacts with numerous receptors.', gold_answer="$\\begingroup$\n\nThere are about 100 [ (Purves, 2001)\n](https://www.ncbi.nlm.nih.gov/books/NBK10824/) to 400 [ (Zozulya _et al_ .,\n2001) ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC33394/) functional **[\nolfactory receptors ](https://senselab.med.yale.edu/ordb/) ** in man. While\nthe total tally of olfactory receptor genes exceeds 1000, more than half of\nthem are [ inactive pseudogenes\n](http://phenomena.nationalgeographic.com/2013/12/11/the-smell-of-evolution/)\n. The combined activity of the expressed functional receptors accounts for the\nnumber of distinct odors that can be discriminated by the human olfactory\nsystem, which is estimated to be about 10,000 [ (Purves, 2001)\n](https://www.ncbi.nlm.nih.gov/books/NBK10824/) .\n\nDifferent receptors are sensitive to subsets of chemicals that define a “ [\ntuning curve ](http://michaeldmann.net/mann8.html) .” Depending on the\nparticular olfactory receptor molecules they contain, some olfactory receptor\nneurons exhibit marked selectivity to particular chemical stimuli, whereas\nothers are activated by a number of different odorant molecules. In addition,\nolfactory receptor neurons can exhibit different thresholds for a particular\nodorant. How these olfactory responses encode a specific odorant is a complex\nissue that is unlikely to be explained at the level of the primary neurons [\n(Purves, 2001) ](https://www.ncbi.nlm.nih.gov/books/NBK10824/) .\n\nSo in a way, the answer to your question is yes, as there are approximately\n100 to 400 olfactory receptors. Just like the photoreceptors in the visual\nsystem, each sensory neuron in the olfactory epithelium in the nose expresses\nonly a single receptor gene ( [ Kimball ](http://www.biology-\npages.info/O/Olfaction.html) ). In the visual system for color vision there\nare just three (red, green and blue cones - RGB) types of sensory neurons, so\nit's a bit more complicated in olfaction.\n\n**References**  \n**-** [ Purves _et al_ , _Neuroscience_ , 2  nd  ed. Sunderland (MA): Sinauer\nAssociates; 2001 ](https://www.ncbi.nlm.nih.gov/books/NBK10824/)  \n**-** [ Zozulya _et al_ ., _Genome Biol_ (2001); **2** (6):\nresearch0018.1–0018.12 ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC33394/)\n\n**Sources**  \n**-** [ Kimball's Biology Pages ](http://www.biology-\npages.info/O/Olfaction.html)")

In [7]:
import pandas as pd
pd.DataFrame(dataset.queries_iter())

,query_id,text,reasoning,gold_answer
0,0,Claim in article about why insects are attract...,The question probes why insects are drawn to l...,$\begingroup$\n\nThey're looking for and descr...
1,1,Why do I only breathe out of one nostril?\nI w...,The post questions the normality of breathing ...,$\begingroup$\n\nApparently you're not the fir...
2,2,Is there an RGB equivalent for smells?\nMillio...,The query explores if basic smells can combine...,$\begingroup$\n\nThere are about 100 [ (Purves...
3,3,Do animals exhibit handedness (paw-ness?) pref...,The question investigates if animals display l...,$\begingroup$\n\n### Short Answer\n\nYes. han...
4,4,What is the evolutionary advantage of red-gree...,The core query here revolves around understand...,$\begingroup$\n\n**Short answer** \nColor-bli...
...,...,...,...,...
98,98,Do teeth have the capacity to heal?\nCould a c...,We can investigate the natural repair capabili...,"$\begingroup$\n\nYes, it can be done to a cert..."
99,99,What creates the feeling of 'excess' blood pre...,We can consider how sensors in our arteries de...,$\begingroup$\n\nArterial Baroreceptors fellin...
100,100,What types of light can't a plant photosynthes...,We can explore how the green pigment in plants...,$\begingroup$\n\nChlorophyll can use a quite b...
101,101,Which part of human eyes is getting tired?\nIt...,We can examine how the muscles responsible for...,$\begingroup$\n\nThese symptoms have a name: C...
102,102,How does yeast dissolve in sugar?\nThere's thi...,We can look into how certain substances natura...,$\begingroup$\n\nThe whole process is called [...

In [8]:
dataset.queries_cls()

ir_datasets.datasets.bright.BrightQuery

In [9]:
dataset.queries_cls()._fields

('query_id', 'text', 'reasoning', 'gold_answer')

In [11]:
dataset.queries_cls().__annotations__

{'query_id': str, 'text': str, 'reasoning': str, 'gold_answer': str}

In [12]:
pd.DataFrame(dataset.qrels_iter())

,query_id,doc_id,relevance,iteration
0,0,insects_attracted_to_light/Proximate_and_ultim...,1,0
1,0,insects_attracted_to_light/Proximate_and_ultim...,1,0
2,0,insects_attracted_to_light/Phototaxis_0.txt,1,0
3,0,insects_attracted_to_light/Phototaxis_3.txt,1,0
4,0,insects_attracted_to_light/Phototaxis_4.txt,1,0
...,...,...,...,...
367,100,plant_light_pho/Chlorophyll_0.txt,1,0
368,100,plant_light_pho/Chlorophyll_2.txt,1,0
369,101,eyes_tired/Computer_vision_syndrome_0.txt,1,0
370,101,eyes_tired/Computer_vision_syndrome_1.txt,1,0
371,102,yeast_dissolve_in_sugar/Osmosis_0.txt,1,0

In [13]:
dataset.qrels_defs()

{1: 'Relevant', -100: 'Excluded from evaluation'}

In [14]:
dataset.qrels_cls()

ir_datasets.formats.trec.TrecQrel

In [15]:
dataset.qrels_cls()._fields

('query_id', 'doc_id', 'relevance', 'iteration')

In [16]:
dataset.qrels_cls().__annotations__

{'query_id': str, 'doc_id': str, 'relevance': int, 'iteration': str}